from .auditorium_repository import AuditoriumRepository
from .discipline_repository import DisciplineRepository
from .group_repository import GroupRepository
from .kind_of_work_repository import KindOfWorkRepository
from .lecturer_repository import LecturerRepository
from .lesson_group_repository import LessonGroupRepository
from .lesson_repository import LessonRepository
from .user_repository import UserRepository